"use strict";

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

module.exports = (function () {
  function GameOpcode() {
    _classCallCheck(this, GameOpcode);
  }

  _createClass(GameOpcode, null, [{
    key: "CMSG_CHAR_ENUM",
    value: 0x0037,
    enumerable: true
  }, {
    key: "SMSG_CHAR_ENUM",
    value: 0x003B,
    enumerable: true
  }, {
    key: "CMSG_PLAYER_LOGIN",
    value: 0x003D,
    enumerable: true
  }, {
    key: "SMSG_CHARACTER_LOGIN_FAILED",
    value: 0x0041,
    enumerable: true
  }, {
    key: "SMSG_LOGIN_SETTIMESPEED",
    value: 0x0042,
    enumerable: true
  }, {
    key: "SMSG_CONTACT_LIST",
    value: 0x0067,
    enumerable: true
  }, {
    key: "CMSG_MESSAGE_CHAT",
    value: 0x0095,
    enumerable: true
  }, {
    key: "SMSG_MESSAGE_CHAT",
    value: 0x0096,
    enumerable: true
  }, {
    key: "SMSG_UPDATE_OBJECT",
    value: 0x00A9,
    enumerable: true
  }, {
    key: "SMSG_MONSTER_MOVE",
    value: 0x00DD,
    enumerable: true
  }, {
    key: "SMSG_TUTORIAL_FLAGS",
    value: 0x00FD,
    enumerable: true
  }, {
    key: "SMSG_INITIALIZE_FACTIONS",
    value: 0x0122,
    enumerable: true
  }, {
    key: "SMSG_SET_PROFICIENCY",
    value: 0x0127,
    enumerable: true
  }, {
    key: "SMSG_ACTION_BUTTONS",
    value: 0x0129,
    enumerable: true
  }, {
    key: "SMSG_INITIAL_SPELLS",
    value: 0x012A,
    enumerable: true
  }, {
    key: "SMSG_SPELL_START",
    value: 0x0131,
    enumerable: true
  }, {
    key: "SMSG_SPELL_GO",
    value: 0x0132,
    enumerable: true
  }, {
    key: "SMSG_BINDPOINT_UPDATE",
    value: 0x0155,
    enumerable: true
  }, {
    key: "SMSG_ITEM_TIME_UPDATE",
    value: 0x01EA,
    enumerable: true
  }, {
    key: "SMSG_AUTH_CHALLENGE",
    value: 0x01EC,
    enumerable: true
  }, {
    key: "CMSG_AUTH_PROOF",
    value: 0x01ED,
    enumerable: true
  }, {
    key: "SMSG_AUTH_RESPONSE",
    value: 0x01EE,
    enumerable: true
  }, {
    key: "SMSG_COMPRESSED_UPDATE_OBJECT",
    value: 0x01F6,
    enumerable: true
  }, {
    key: "SMSG_ACCOUNT_DATA_TIMES",
    value: 0x0209,
    enumerable: true
  }, {
    key: "SMSG_LOGIN_VERIFY_WORLD",
    value: 0x0236,
    enumerable: true
  }, {
    key: "SMSG_SPELL_NON_MELEE_DAMAGE_LOG",
    value: 0x0250,
    enumerable: true
  }, {
    key: "SMSG_INIT_WORLD_STATES",
    value: 0x02C2,
    enumerable: true
  }, {
    key: "SMSG_UPDATE_WORLD_STATE",
    value: 0x02C3,
    enumerable: true
  }, {
    key: "SMSG_WEATHER",
    value: 0x02F4,
    enumerable: true
  }, {
    key: "MSG_SET_DUNGEON_DIFFICULTY",
    value: 0x0329,
    enumerable: true
  }, {
    key: "SMSG_UPDATE_INSTANCE_OWNERSHIP",
    value: 0x032B,
    enumerable: true
  }, {
    key: "SMSG_INSTANCE_DIFFICULTY",
    value: 0x033B,
    enumerable: true
  }, {
    key: "SMSG_MOTD",
    value: 0x033D,
    enumerable: true
  }, {
    key: "SMSG_TIME_SYNC_REQ",
    value: 0x0390,
    enumerable: true
  }, {
    key: "SMSG_FEATURE_SYSTEM_STATUS",
    value: 0x03C9,
    enumerable: true
  }, {
    key: "SMSG_SERVER_BUCK_DATA",
    value: 0x041D,
    enumerable: true
  }, {
    key: "SMSG_SEND_UNLEARN_SPELLS",
    value: 0x041E,
    enumerable: true
  }, {
    key: "SMSG_LEARNED_DANCE_MOVES",
    value: 0x0455,
    enumerable: true
  }, {
    key: "SMSG_ALL_ACHIEVEMENT_DATA",
    value: 0x047D,
    enumerable: true
  }, {
    key: "SMSG_POWER_UPDATE",
    value: 0x0480,
    enumerable: true
  }, {
    key: "SMSG_AURA_UPDATE_ALL",
    value: 0x0495,
    enumerable: true
  }, {
    key: "SMSG_AURA_UPDATE",
    value: 0x0496,
    enumerable: true
  }, {
    key: "SMSG_EQUIPMENT_SET_LIST",
    value: 0x04BC,
    enumerable: true
  }, {
    key: "SMSG_TALENTS_INFO",
    value: 0x04C0,
    enumerable: true
  }, {
    key: "MSG_SET_RAID_DIFFICULTY",
    value: 0x04EB,
    enumerable: true
  }]);

  return GameOpcode;
})();