Wowser.Expansion.WotLK.Enums.WorldOpcode = (function() {
  function WorldOpcode() {}

  WorldOpcode.CMSG_CHAR_ENUM = 0x0037;

  WorldOpcode.SMSG_CHAR_ENUM = 0x003B;

  WorldOpcode.CMSG_PLAYER_LOGIN = 0x003D;

  WorldOpcode.SMSG_CHARACTER_LOGIN_FAILED = 0x0041;

  WorldOpcode.SMSG_LOGIN_SETTIMESPEED = 0x0042;

  WorldOpcode.SMSG_CONTACT_LIST = 0x0067;

  WorldOpcode.CMSG_MESSAGE_CHAT = 0x0095;

  WorldOpcode.SMSG_MESSAGE_CHAT = 0x0096;

  WorldOpcode.SMSG_UPDATE_OBJECT = 0x00A9;

  WorldOpcode.SMSG_MONSTER_MOVE = 0x00DD;

  WorldOpcode.SMSG_TUTORIAL_FLAGS = 0x00FD;

  WorldOpcode.SMSG_INITIALIZE_FACTIONS = 0x0122;

  WorldOpcode.SMSG_SET_PROFICIENCY = 0x0127;

  WorldOpcode.SMSG_ACTION_BUTTONS = 0x0129;

  WorldOpcode.SMSG_INITIAL_SPELLS = 0x012A;

  WorldOpcode.SMSG_SPELL_START = 0x0131;

  WorldOpcode.SMSG_SPELL_GO = 0x0132;

  WorldOpcode.SMSG_BINDPOINT_UPDATE = 0x0155;

  WorldOpcode.SMSG_ITEM_TIME_UPDATE = 0x01EA;

  WorldOpcode.SMSG_AUTH_CHALLENGE = 0x01EC;

  WorldOpcode.CMSG_AUTH_PROOF = 0x01ED;

  WorldOpcode.SMSG_AUTH_RESPONSE = 0x01EE;

  WorldOpcode.SMSG_COMPRESSED_UPDATE_OBJECT = 0x01F6;

  WorldOpcode.SMSG_ACCOUNT_DATA_TIMES = 0x0209;

  WorldOpcode.SMSG_LOGIN_VERIFY_WORLD = 0x0236;

  WorldOpcode.SMSG_SPELL_NON_MELEE_DAMAGE_LOG = 0x0250;

  WorldOpcode.SMSG_INIT_WORLD_STATES = 0x02C2;

  WorldOpcode.SMSG_UPDATE_WORLD_STATE = 0x02C3;

  WorldOpcode.SMSG_WEATHER = 0x02F4;

  WorldOpcode.MSG_SET_DUNGEON_DIFFICULTY = 0x0329;

  WorldOpcode.SMSG_UPDATE_INSTANCE_OWNERSHIP = 0x032B;

  WorldOpcode.SMSG_INSTANCE_DIFFICULTY = 0x033B;

  WorldOpcode.SMSG_MOTD = 0x033D;

  WorldOpcode.SMSG_TIME_SYNC_REQ = 0x0390;

  WorldOpcode.SMSG_FEATURE_SYSTEM_STATUS = 0x03C9;

  WorldOpcode.SMSG_SERVER_BUCK_DATA = 0x041D;

  WorldOpcode.SMSG_SEND_UNLEARN_SPELLS = 0x041E;

  WorldOpcode.SMSG_LEARNED_DANCE_MOVES = 0x0455;

  WorldOpcode.SMSG_ALL_ACHIEVEMENT_DATA = 0x047D;

  WorldOpcode.SMSG_POWER_UPDATE = 0x0480;

  WorldOpcode.SMSG_AURA_UPDATE_ALL = 0x0495;

  WorldOpcode.SMSG_AURA_UPDATE = 0x0496;

  WorldOpcode.SMSG_EQUIPMENT_SET_LIST = 0x04BC;

  WorldOpcode.SMSG_TALENTS_INFO = 0x04C0;

  WorldOpcode.MSG_SET_RAID_DIFFICULTY = 0x04EB;

  return WorldOpcode;

})();
