var GameOpcode;

GameOpcode = (function() {
  function GameOpcode() {}

  module.exports = GameOpcode;

  GameOpcode.CMSG_CHAR_ENUM = 0x0037;

  GameOpcode.SMSG_CHAR_ENUM = 0x003B;

  GameOpcode.CMSG_PLAYER_LOGIN = 0x003D;

  GameOpcode.SMSG_CHARACTER_LOGIN_FAILED = 0x0041;

  GameOpcode.SMSG_LOGIN_SETTIMESPEED = 0x0042;

  GameOpcode.SMSG_CONTACT_LIST = 0x0067;

  GameOpcode.CMSG_MESSAGE_CHAT = 0x0095;

  GameOpcode.SMSG_MESSAGE_CHAT = 0x0096;

  GameOpcode.SMSG_UPDATE_OBJECT = 0x00A9;

  GameOpcode.SMSG_MONSTER_MOVE = 0x00DD;

  GameOpcode.SMSG_TUTORIAL_FLAGS = 0x00FD;

  GameOpcode.SMSG_INITIALIZE_FACTIONS = 0x0122;

  GameOpcode.SMSG_SET_PROFICIENCY = 0x0127;

  GameOpcode.SMSG_ACTION_BUTTONS = 0x0129;

  GameOpcode.SMSG_INITIAL_SPELLS = 0x012A;

  GameOpcode.SMSG_SPELL_START = 0x0131;

  GameOpcode.SMSG_SPELL_GO = 0x0132;

  GameOpcode.SMSG_BINDPOINT_UPDATE = 0x0155;

  GameOpcode.SMSG_ITEM_TIME_UPDATE = 0x01EA;

  GameOpcode.SMSG_AUTH_CHALLENGE = 0x01EC;

  GameOpcode.CMSG_AUTH_PROOF = 0x01ED;

  GameOpcode.SMSG_AUTH_RESPONSE = 0x01EE;

  GameOpcode.SMSG_COMPRESSED_UPDATE_OBJECT = 0x01F6;

  GameOpcode.SMSG_ACCOUNT_DATA_TIMES = 0x0209;

  GameOpcode.SMSG_LOGIN_VERIFY_WORLD = 0x0236;

  GameOpcode.SMSG_SPELL_NON_MELEE_DAMAGE_LOG = 0x0250;

  GameOpcode.SMSG_INIT_WORLD_STATES = 0x02C2;

  GameOpcode.SMSG_UPDATE_WORLD_STATE = 0x02C3;

  GameOpcode.SMSG_WEATHER = 0x02F4;

  GameOpcode.MSG_SET_DUNGEON_DIFFICULTY = 0x0329;

  GameOpcode.SMSG_UPDATE_INSTANCE_OWNERSHIP = 0x032B;

  GameOpcode.SMSG_INSTANCE_DIFFICULTY = 0x033B;

  GameOpcode.SMSG_MOTD = 0x033D;

  GameOpcode.SMSG_TIME_SYNC_REQ = 0x0390;

  GameOpcode.SMSG_FEATURE_SYSTEM_STATUS = 0x03C9;

  GameOpcode.SMSG_SERVER_BUCK_DATA = 0x041D;

  GameOpcode.SMSG_SEND_UNLEARN_SPELLS = 0x041E;

  GameOpcode.SMSG_LEARNED_DANCE_MOVES = 0x0455;

  GameOpcode.SMSG_ALL_ACHIEVEMENT_DATA = 0x047D;

  GameOpcode.SMSG_POWER_UPDATE = 0x0480;

  GameOpcode.SMSG_AURA_UPDATE_ALL = 0x0495;

  GameOpcode.SMSG_AURA_UPDATE = 0x0496;

  GameOpcode.SMSG_EQUIPMENT_SET_LIST = 0x04BC;

  GameOpcode.SMSG_TALENTS_INFO = 0x04C0;

  GameOpcode.MSG_SET_RAID_DIFFICULTY = 0x04EB;

  return GameOpcode;

})();
